server:
  error:
    include-stacktrace: never

spring:
  datasource:
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    url: ${JDBC_DATABASE_URL}

  jpa:
    show-sql: false

    hibernate:
      ddl-auto: validate

logging:
  level:
    ROOT: INFO