server:
  port: ${PORT:5000}

base-url: /api

spring:
  profiles:
    active: dev

  application:
    name: taskManager

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml

  jpa:
    generate-ddl: true